# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2018-03-15 11:37
from __future__ import unicode_literals

import Fact.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.CharField(max_length=60, unique=True)),
                ('icon', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=Fact.models.path_and_rename, verbose_name='Path')),
                ('description', models.CharField(blank=True, max_length=160)),
                ('path_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('parent', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_category', to='Fact.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guess', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('content', models.TextField()),
                ('pub_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Fact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(unique=True)),
                ('source', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('pub_date', models.DateField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to=Fact.models.path_and_rename, verbose_name='Path')),
                ('path_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_base', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='aaa', max_length=60)),
                ('title', models.CharField(max_length=160, unique=True)),
                ('slug', models.CharField(max_length=160, unique=True)),
                ('description', models.TextField(default=None, null=True)),
                ('pub_date', models.DateField(auto_now=True)),
                ('image', versatileimagefield.fields.VersatileImageField(blank=True, upload_to=Fact.models.path_and_rename, verbose_name='Path')),
                ('path_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='category', to='Fact.Category')),
            ],
        ),
        migrations.AddField(
            model_name='fact',
            name='object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object', to='Fact.Object'),
        ),
        migrations.AddField(
            model_name='confirm',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_confirm', to='Fact.Fact'),
        ),
        migrations.AddField(
            model_name='confirm',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member_confirm', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='fact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fact_comment', to='Fact.Fact'),
        ),
        migrations.AddField(
            model_name='comment',
            name='member',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='member_comment', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_comment', to='Fact.Comment'),
        ),
    ]
